[tasks.argocd]
run = '''
kubectl create namespace bootstrap
kubectl apply -n bootstrap -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
'''
depends = ["gkecred"]

[tasks.argocdexpose]
run = '''
kubectl patch svc argocd-server -n bootstrap -p "{\"spec\": {\"type\": \"LoadBalancer\"}}"
argocd admin initial-password -n bootstrap
'''
depends = ["gkecred"]

[tasks."config-connector"]
run = '''
gcloud storage cp gs://configconnector-operator/latest/release-bundle.tar.gz release-bundle.tar.gz
tar zxvf release-bundle.tar.gz
kubectl apply -f operator-system/autopilot-configconnector-operator.yaml
kubectl apply -f configconnector.yaml
'''
depends = ["gkecred"]

[tasks.argocdready]
run = '''
argocd repo add https://github.com/takahiroaoki/gcp-playground.git --username oauth2 --password $(cat pat.txt)
kubectl apply -f argocd-role.yaml
kubectl apply -f root.yaml
'''
depends = ["gkecred"]

[tasks.deploy]
depends = [
	'config-connector',
	'argocdready'
]